/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_papan01_livestreamer_Live555Native */

#ifndef _Included_edu_papan01_livestreamer_Live555Native
#define _Included_edu_papan01_livestreamer_Live555Native
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_papan01_livestreamer_Live555Native
 * Method:    initialize
 * Signature: (II)Z
 */
JNIEXPORT jboolean JNICALL Java_edu_papan01_livestreamer_Live555Native_initialize
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     edu_papan01_livestreamer_Live555Native
 * Method:    loopNative
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_edu_papan01_livestreamer_Live555Native_loopNative
  (JNIEnv *, jobject);

/*
 * Class:     edu_papan01_livestreamer_Live555Native
 * Method:    stopNative
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_edu_papan01_livestreamer_Live555Native_stopNative
  (JNIEnv *, jobject);

/*
 * Class:     edu_papan01_livestreamer_Live555Native
 * Method:    feedH264Data
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_edu_papan01_livestreamer_Live555Native_feedH264Data
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     edu_papan01_livestreamer_Live555Native
 * Method:    destroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_edu_papan01_livestreamer_Live555Native_destroy
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
